#
# The ProFTPD Website Makefile
#

include ../Common.defines

SEPDIRS =
SUBDIRS =
HTMLFILES = $(addsuffix .html, $(basename $(wildcard *.epl)))
OUTDIR = /home/jwm/public_html/www.proftpd.org/docs/

# Top level targets

all: html

include ../Common.targets
