#
# The ProFTPD Website Makefile
#

include ../Common.defines

SEPDIRS =
SUBDIRS =
HTMLFILES = $(addsuffix .html, $(basename $(wildcard *.epl)))
#INFILES = Common.defines scripts/macrodefs.m4
#CONFIGURE = $(SOURCEROOT)/configure

# Top level targets

all : html

include ../Common.targets


