#
# The ProFTPD Website Makefile
#

include ../Common.defines

SEPDIRS =
SUBDIRS =
HTMLFILES = $(addsuffix .html, $(basename $(wildcard *.epl)))

# Top level targets

all: html

include ../Common.targets
